### ISSUE TITLE
Test Fwk: Add conversions for ScVal<=>Into<RawVal>

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-env#106]
We should add a `impl TryFrom<ScVal> for RawVal` that can convert an `ScVal` to a `RawVal`. It wouldn't be able to support all types but it could support all but the `SCV_OBJECT` arm.

For the XDR types that parallel types that are `RawValConvertible` we should also add a `impl From<_> for RawVal`. This would be for any arm that has a non-builtin type. i.e. `SCV_STATIC`, `SCV_SYMBOL`, and `SCV_STATUS`.

We can also implement conversions in the opposite direction and most will be symmetrical, except the `SCV_POS_I64` arm that would not be able to convert the other way for negative values of int64.

@jonjove asked for how to do these conversions in a meeting today. @graydon suggested we should have this in the common package.

cc @jonjove @graydon

**Comment by leighmcculloch** [comment]
@jonjove What were you needing this for?

**Comment by graydon** [comment]
I want the WeakHost type not to escape the host crate. I'm not as concerned about the general concept of conversion, though I suspect it will confuse users that some-but-not-all SCVals can be converted without an Env.

**Comment by leighmcculloch** [comment]
>I want the WeakHost type not to escape the host crate. I'm not as concerned about the general concept of conversion

Ah ok, I think I misunderstood your prior comment.

>I suspect it will confuse users that some-but-not-all SCVals can be converted without an Env.

I planned to only implement the to and from EnvVal conversions, not the RawVal.

I'll revive #81 then.

**Comment by leighmcculloch** [comment]
If possible we should make this for conversions from `ScVal` from/to `IntoEnvVal<E, V>` so that we can seamless convert SDK types to and from ScVal types. This is requires for making #240 usable on all types of UDTs, since UDTs can contain SDK types.
