### ISSUE TITLE
Add Eq/PartialEq impls for Val, Object, etc

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-env#13]

**Comment by leighmcculloch** [comment]
@graydon I transfer this issue from the sdk repo to the host repo, because I think this will need implementing here now instead? Please lmk if I understand this incorrectly.

**Comment by graydon** [comment]
Yeah, I've implemented the deep equality inside the HostContext but I haven't surfaced it to users yet (in the form of a host function). We'll need to add host functions for them, and then wire up implementations of `Eq` and `Ord` and such in the client types to call through to the host functions.

**Comment by leighmcculloch** [comment]
@graydon Should this be assigned to @jayz22 moving forward if this is at the hostfn point?

**Comment by graydon** [comment]
It's a host function at this point -- `obj_cmp`

**Comment by leighmcculloch** [comment]
Ah sweet. Reopened and assigned to me, I'll plumb it into the types.

**Comment by leighmcculloch** [comment]
Looks like someone, maybe @graydon?, already plumbed most of it. I just added it to vec/map in https://github.com/stellar/rs-stellar-contract-sdk/pull/124.
