### ISSUE TITLE
Errors: Break down ConversionError to unique error types or include source and destination types

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-stellar-contract-env#158]
https://github.com/stellar/rs-stellar-contract-env/pull/142#discussion_r906734989

**Comment by leighmcculloch** [comment]
Or include information about what the to and from types are in the conversion inside the error, which might scale better especially across the env and sdk boundaries without us needing to introduce dyn traits.

**Comment by jayz22** [comment]
Currently blocked by https://github.com/stellar/rs-stellar-contract-env/issues/205 . Once the "diagnostic vs error handling split" is done, the type and RawVal information will go to error logging and the `ConversionError` will go back to being a minimal type.

**Comment by jayz22** [comment]
Updated to in-progress.

**Comment by jayz22** [comment]
To summarize the key points in today's discussion with @graydon and @leighmcculloch 
Following Graydon's work last week https://github.com/stellar/rs-stellar-contract-env/pull/220, the error status and debug information are now split. The `ConversionError` as currently structured (an empty `Struct`) is only capturing the error status part. The effort in this issue is to build in the debug information which includes the source and destination types where the conversion fails. 
Such debug information will be included in the form of `DebugEvent`s, and the `ConversionError` structure will remain the same. 
- On the host side: everywhere where `ConversionError` is generated, log the debug information as a `DebugEvent`. 
- On the guest side: before `ConversionError` is returned, call the host functions to log the debug information.
- If an `EnvVal` conversion fails, always call the log function on the `env` to log the diagnostic information. 
- The host will provide a wider variety of host functions for error related logging, with different number of arguments, or relating to different types where conversion fail. The advantage of this versus having just one generic logging function that takes variable length arguments is the efficiency in WASM code size (i.e. avoiding one `push` for passing each additional arg). The main trade-off is the larger number of host functions to maintain but we believe it is a worthy one. 

I will update https://github.com/stellar/rs-stellar-contract-env/issues/168 and https://github.com/stellar/rs-stellar-contract-sdk/pull/208 to incorporate the above points.
