### ISSUE TITLE
Fix Serialization Functions

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-stellar-contract-env#167]
### What did you expect to see?

`serialize_to_binary` and `deserialize_from_binary` should operate on values. Their implementations should match CAP-0051.

### What did you see instead?

They operate on objects, and `deserialize_from_binary` does not have the signature specified in CAP-0051 (the CAP is wrong).

**Comment by jayz22** [comment]
Resolved by https://github.com/stellar/rs-stellar-contract-env/pull/176.
