### ISSUE TITLE
Errors: Include source and destination types in ConversionErrors

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-env#168]

**Comment by jayz22** [comment]
Is this duplicate issue with https://github.com/stellar/rs-stellar-contract-env/issues/158?  You mentioned this as a possible approach in the comment, do we still need that issue?

**Comment by leighmcculloch** [comment]
Oops. You're right. This is a duplicate. I'll close this one and update the other if that's okay.
