### ISSUE TITLE
Type: Vec: Add capacity parameter to vec_new

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-env#196]
We discussed this previously and I think it fell through teh cracks. We'll be using Vecs in situations where the size of the vec will be known ahead of time and probably very small. It will be ideal if the SDK can inform the host of what that size will be so it can be used as the capacity.

The `vec_new` fn should be changed to accept a capacity as a u32. If the STATIC_VOID value is passed the host should assume no value has been passed.

It'll be easier to make this change now.

cc @graydon @jayz22

**Comment by leighmcculloch** [comment]
Do we need this for maps too?

**Comment by jayz22** [comment]
This was previously discussed in [Discord thread]( https://discord.com/channels/897514728459468821/989537434381463612/989610787544899654).
Just to clarify, we will be adding the parameter to the function interface but no optimization? The im-rc implementation uses RRB vector which does not take capacity. We will in the future use the capacity parameter for small vector optimization (e.g. using std::Vec for capacity below a threshold).

**Comment by jayz22** [comment]
Or does the scope cover the optimization, i.e. making decision related to the size threshold etc. ?

**Comment by jayz22** [comment]
Also, STATIC_VOID is ok (rather than STATIC_NONE)?

**Comment by leighmcculloch** [comment]
STATIC_NONE would be better but it hasn't been implemented yet, and this interface is hidden so it doesn't really matter which it is.

>but no optimization?
Yeah no optimization, the intent is to add the parameter now so that we can optimize it later on, and we can start passing in the value on the SDK side.

I had originally suggested it be a new function, and @graydon pointed out we should just make it the existing fn and add the parameter which could optional.
